<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings("ignore")


print ('imported successful!')

imported successful!


In [2]:
def info(data, name):
'''функция выводит общую инфо о датасете, количество дублей, пропусков
data = имя файла
name = название файла'''

    start = "\033[1m"
    end = "\033[0;0m"

    print (start + 'Общая информация', name + end)
    print(data.info())
    print (start + 'Первые 5 строк', name + end)
    display(data.head())
    print (start + 'Описательные статистики', name + end)
    display(data.describe())
    print (start + 'Количество дубликатов', name + end)
    print(data.duplicated().sum())
    print (start + 'Количество пропусков', name + end)
    print(data.isna().sum())

In [3]:
def read(pth1, pth2, name):
'''функция читает файлы csv из указанного места и вызывает в себе функцию info, которая описана в предыдущей ячейке
pth1 = место файла 1
pth2 = место файла 2'''

    if os.path.exists(pth1):
        data = pd.read_csv(pth1)
        info(data, name)
    elif os.path.exists(pth2):
        data = pd.read_csv(pth2)
        info(data, name)
    else:
        print('File Not Found')
    return data

In [4]:
pd.set_option('display.max_columns', None) #сброс ограничений на количество выводимых столбцов
pd.set_option('display.max_rows', None) #сброс ограничений на количество выводимых рядов
pd.options.display.float_format = '{:,.2f}'.format #ограничение на кол-во знаков после запятой у float - переменныхb

In [5]:
data = read('/file.csv', '/', 'Датасет')

Общая информация Датасет
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
None
Первые 5 строк Датасет


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1    41.00 49,600.00            1                  0
1    0    46.00 38,000.00            1                  1
2    0    29.00 21,000.00            0                  0
3    0    21.00 41,700.00            2                  0
4    1    28.00 26,100.00            0                  0

Описательные статистики Датасет


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
count 5,000.00 5,000.00  5,000.00     5,000.00           5,000.00
mean      0.50    30.95 39,916.36         1.19               0.15
std       0.50     8.44  9,900.08         1.09               0.46
min       0.00    18.00  5,300.00         0.00               0.00
25%       0.00    24.00 33,300.00         0.00               0.00
50%       0.00    30.00 40,200.00         1.00               0.00
75%       1.00    37.00 46,600.00         2.00               0.00
max       1.00    65.00 79,000.00         6.00               5.00

Количество дубликатов Датасет
153
Количество пропусков Датасет
Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64


В датасете имеем 5 признаков(столбцы) и 5000 наблюдений. Встречаются дубли в данных. Аномальные значения не обнаружены.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** не изменится



**Обоснование:** 

1. Для обоснования ответа получим предсказания для признаков после множения на обратимую матрицу. Умноженная матрица будет иметь вид X*P (XP). Тогда формула предсказаний (линейной регрессии) примет следующий вид:


$$
a =  XP *(((XP)^T * (XP))^{-1} * (XP)^T * y)
$$

2. Раскроем скобки и уберем их, где допустимо.

$$
a =  XP *(X^T P^T * XP)^{-1} * X^T P^T * y
$$

3. Можно использовать свойство матриц $(AB)C = A(BC)$. Оно позволяет группировать матрицы при умножении различным образом. Вынесем за скобки множитель $P$:

$$
a =  XP * P^{-1} (X^T P^T * X)^{-1} * X^T * P^T * y
$$

4. Вынесем за скобки множитель $P^T$:

$$
a =  XP * P^{-1} * (P^T)^{-1} (X^T* X)^{-1} * X^T * P^T * y
$$

5. Произведения $P*P^{-1}$ и  $P^T(P^T)^{-1}$ дают единичную матрицу, которую можно исключить из уравнения:

$$
a =  X * (X^T* X)^{-1} * X^T *  y
$$

6. И получается, что $(X^T* X)^{-1} * X^T *  y = w$, и наша формула предсказаний регрессии вернулась к исходному виду:

$$
a = Xw
$$

## Алгоритм преобразования

**Алгоритм**

В качестве алгоритма преобразования примем умножение обучающих признаков X (их размерность - 5000 на 4) на случайную обратимую матрицу P (размером 4х4). Создадим модель линейной регрессии до преобразования и посчитаем метрику R2. Далее умножим исходные признаки на обратимую матрицу и на основе полученных значений вновь посчитаем метрику R2. Метрики R2 по итогу должны быть равны.

**Обоснование**

Как было доказано, умножение признаков на какую-либо обратимую матрицу не приводит к изменению предсказаний, поэтому результаты R2 должны оказаться равны.

## Проверка алгоритма

In [6]:
# создадим признаки для исходного состояния
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты'] #целевой признак
print(features.head())

   Пол  Возраст  Зарплата  Члены семьи
0    1    41.00 49,600.00            1
1    0    46.00 38,000.00            1
2    0    29.00 21,000.00            0
3    0    21.00 41,700.00            2
4    1    28.00 26,100.00            0


In [7]:
# обучим модель, предскажем значения target и измерим r2
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
r2 = r2_score(target, predictions)
print(f'Метрика R2 для матрицы X равняется {r2}')

Метрика R2 для матрицы X равняется 0.4249455028666801


Далее необходимо создать обратимую матрицу размером 4 на 4. Почему 4х4? Потому что при умножении важно, чтобы число столбцов было равно числу строк первой марицы - матрицы признаков. 

При этом важно не создать случайно необратимую матрицу. Для существования обратимой матрицы  необходимо, чтобы ее определитель не был равен нулю.

In [8]:
P = np.random.normal(size=(4, 4))
det = np.linalg.det(P)
if det ==0:
    P = np.random.normal(size=(4, 4))
print(P)
print(det)

[[-2.36873882  0.9579563  -1.02719207 -1.56317302]
 [ 1.36710555 -0.10264808  1.77441158 -0.30366769]
 [-0.29200443  0.07068886  1.73423282  0.63422684]
 [-0.62700962  1.02728952 -0.86374537  1.38463307]]
-10.152677504730708


In [9]:
features_2 = features @ P
features_2.head()

0        1         2         3
0 -14,430.36 3,503.94 86,088.81 31,445.02
1 -11,033.91 2,682.48 65,981.61 24,088.04
2  -6,092.45 1,481.49 36,470.35 13,309.96
3 -12,149.13 2,947.62 72,353.04 26,443.65
4  -7,585.41 1,843.06 45,312.13 16,543.25

Произведем моделирование на измененных признаках.

In [10]:
model_2 = LinearRegression()
model_2.fit(features_2, target)
predictions = model_2.predict(features_2)
r2_2 = r2_score(target, predictions)
print(f'Метрика R2 для матрицы XP равняется {r2_2}')

Метрика R2 для матрицы XP равняется 0.4249455028666791


Метрики R2 обеих моделей почти одинаковые, следовательно умножение исходных данных на случайную обратимую матрицу может быть применено для их шифрования.